### PR TITLE
Work on resolution by Claim ID

### PR DESCRIPTION
**Pull request by kaykurokawa**
Work in progress to allow lbryum server to resolve claims by claim ID. 

This is done by storing claim id's in the key value database , where claim id's are the key and the value contains the outpoint of the claim (txid + nout). 

The value of a claim can then be retrieved by using getclaimsfortx command in lbrycrd 

This requires a rebuild of the lbryum server.

### CODE REVIEW

**Comment by kaykurokawa** [comment]
Server update instruction: 

Delete contents of lbryum server data folder (in /var/lbryum-server )

Do not allow clients to connect while updating , otherwise server will crash ( either block port 50001 or set stratum_tcp_port in /etc/lbryum.conf to some other port) 

Run "lbryum-server start" and it will start to rebuild database. Takes about two hours.

**Comment by jackrobison** [comment]
Is this a WIP? Good to merge?

**Comment by kaykurokawa** [comment]
I need to start up a test server with this pull request which I will post the IP for when ready

**Comment by jobevers** [comment]
How much work is left on this?

**Comment by lyoshenka** [comment]
whats the next step? it sounds like this needs to be tested, correct?

**Pull request closed without merging**
